#!/bin/bash

development_environment_setup_main(){
	local root
	root=/home/sakai

	development_environment_setup_dotfiles

	development_environment_setup_plugins
	development_environment_setup_vim

	development_environment_download_direnv
}

development_environment_setup_dotfiles(){
	local dir
	local repo

	dir=$root
	repo=git://github.com/shun-fix9/dotfiles
	development_environment_setup_git_sync "."
}

development_environment_setup_plugins(){
	local dir
	local repo

	dir=$root/plugins
	mkdir -p $dir

	local -a repos=(
		git://github.com/shun-fix9/mybashrc
		git://github.com/shun-fix9/myprocesses
		git://github.com/shun-fix9/findword
		git://github.com/sanzen-sekai/mypassword
		git://github.com/sanzen-sekai/git-readme
		git://github.com/sanzen-sekai/git-pub
		git://github.com/sanzen-sekai/git-sub-status
		git://github.com/sanzen-sekai/git-post
	)
	for repo in ${repos[@]}; do
		development_environment_setup_git_sync
	done
}
development_environment_setup_vim(){
	local dir
	local repo
	local file

	dir=$root/.vim/bundle
	mkdir -p $dir

	local -a repos=(
		git://github.com/tpope/vim-pathogen
		git://github.com/tpope/vim-fugitive
		git://github.com/tpope/vim-endwise
		git://github.com/msanders/snipmate.vim
		git://github.com/edsono/vim-matchit
		git://github.com/plasticboy/vim-markdown
		git://github.com/kchmck/vim-coffee-script
		git://github.com/cakebaker/scss-syntax.vim
		git://github.com/tpope/vim-cucumber
		git://github.com/tpope/vim-rails
		git://github.com/vim-ruby/vim-ruby
		git://github.com/jpo/vim-railscasts-theme.git
	)
	for repo in ${repos[@]}; do
		development_environment_setup_git_sync
	done

	dir=$root/.vim/autoload
	mkdir -p $dir
	cd $dir

	for file in ../bundle/*/autoload/*; do
		if [ -f $file ]; then
			if [ ! -L "$(basename $file)" ]; then
				ln -s $file
			fi
		fi
	done
}

development_environment_setup_git_sync(){
	local name
	if [ -n "$1" ]; then
		name=$1
	else
		name=$(basename $repo)
	fi

	echo "$repo => $dir/$name"

	cd $dir
	if [ $name = "." ]; then
		if [ -d .git ]; then
			git pull
		else
			git clone $repo tmp_git_repo
			mv tmp_git_repo/.git .
			rm -rf tmp_git_repo
			git checkout .
		fi
	else
		if [ -d $name ]; then
			cd $name
			git pull
		else
			git clone $repo $name
		fi
	fi
}

development_environment_download_direnv(){
	mkdir -p $root/plugins/direnv/bin
	curl -fsSL https://github.com/direnv/direnv/releases/download/v2.8.1/direnv.linux-amd64 > $root/plugins/direnv/bin/direnv
	chmod a+x $root/plugins/direnv/bin/direnv
}

development_environment_setup_main
